### ISSUE TITLE
Unable to resolve github.com

### ISSUE THREAD

**Issue by Keulen** [hanze-hbo-ict/sw_sec_docs#1]
Issue: Unable to resolve github.com in WSL,  opdracht week 1

Oplossing:
sudo nano /etc/resolv.conf
comment originele nameserver (met #)
nameserver 8.8.8.8
nameserver 8.8.4.4
ctrl o , ctrl x

Source:
https://stackoverflow.com/questions/55649015/could-not-resolve-host-github-com-only-in-windows-bash

**Comment by bart314** [comment]
Dit is niet alleen een issue, maar ook gelijk een oplossing (als ik het goed begrijp). Het is beter om direct de betreffende code aan te passen en een PR te doen, lijkt me.
